package com.example.chiguaapp;

import org.json.*;import java.io.*;import java.net.*;import java.util.*;import java.util.regex.*;

public class Scraper{
    public static final String[] CLASS_NAMES = "今日吃瓜&学生校园&网红黑料&热门大瓜&吃瓜榜单&必看大瓜&看片娱乐&每日大赛&伦理道德&国产剧情&网黄合集&探花精选&免费短剧&骚男骚女&明星黑料&海外吃瓜&人人吃瓜&领导干部&吃瓜看戏&擦边聊骚&51涨知识&51品茶&原创博主&51剧场".split("&");
    public static final String[] CLASS_URLS = "wpcz&xsxy&whhl&rdsj&mrdg&bkdg&ysyl&mrds&lldd&gcjq&whhj&thjx&cbdj&snsn&whmx&hwcg&rrcg&ldcg&qubk&dcbq&zzs&51by&yczq&51djc".split("&");
    static String[] HOSTS={"https://band.nnfndyhn.cc","https://band.bdleshd.cc","https://band.azoxidnu.cc","https://band.atvfvqjv.cc","http://band.atvfvqjv.cc","http://chigua.com","https://chigua.com"};
    static String currentHost=HOSTS[0];
    public static void useSource(SourceConfig sc){ if(sc!=null){ HOSTS=sc.hosts; currentHost=sc.host; } }
    public static class Detail{String title="详情", content=""; ArrayList<PlayItem> plays=new ArrayList<>();}
    public static ArrayList<VideoItem> home() throws Exception{return loadPath("/");}
    public static ArrayList<VideoItem> category(String id,int page)throws Exception{return loadPath("/category/"+id+"/"+page+"/");}
    public static ArrayList<VideoItem> search(String kw,int page)throws Exception{return loadPath("/search/"+URLEncoder.encode(kw,"UTF-8")+"/"+page+"/");}
    static ArrayList<VideoItem> loadPath(String path)throws Exception{String html=""; for(String h:HOSTS){try{currentHost=h; html=http(h+path); if(html.contains("/archives/"))break;}catch(Exception ignored){}} return parseList(html);}
    static String http(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection(); c.setConnectTimeout(15000); c.setReadTimeout(15000); c.setRequestProperty("User-Agent","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36"); c.setRequestProperty("Referer",currentHost+"/"); InputStream is=c.getResponseCode()>=400?c.getErrorStream():c.getInputStream(); ByteArrayOutputStream out=new ByteArrayOutputStream(); byte[] buf=new byte[8192]; int n; while((n=is.read(buf))>0)out.write(buf,0,n); return out.toString("UTF-8");}
    static ArrayList<VideoItem> parseList(String html){ArrayList<VideoItem> out=new ArrayList<>(); HashSet<String> seen=new HashSet<>(); int pos=0; while(true){int a=html.indexOf("/archives/",pos); if(a<0)break; pos=a+10; int hs=html.lastIndexOf("href=",a); if(hs<0||a-hs>220)continue; char q=html.charAt(hs+5); if(q!='\"'&&q!='\'')continue; int he=html.indexOf(q,hs+6); if(he<0)continue; String url=abs(html.substring(hs+6,he)); if(seen.contains(url))continue; int art=html.lastIndexOf("<article",a); if(art<0||a-art>8000)continue; int end=html.indexOf("</article>",a); if(end<0||end-art>9000)end=Math.min(html.length(),a+5000); String seg=html.substring(art,end); if(!seg.contains("post-card-title"))continue; String title=txt(betweenTag(seg,"<h2","</h2>")).replace("热搜 HOT",""); String desc=""; int ip=seg.indexOf("post-card-info"); if(ip>=0){int ds=seg.lastIndexOf("<div",ip); int de=seg.indexOf("</div>",ip); if(ds>=0&&de>ds)desc=txt(seg.substring(ds,de+6));} String img=abs(pic(seg)); if(title.length()>0){seen.add(url); out.add(new VideoItem(title,url,img,desc));}} return out;}
    public static Detail detail(String url)throws Exception{String html=http(url); Detail d=new Detail(); d.title=txt(betweenTag(html,"<h1","</h1>")); String meta=meta(html,"description"); d.content=txt(meta); String[] bs=html.split("class=\\\"dplayer\\\""); for(int i=1;i<bs.length;i++){String block=bs[i]; String vt=cut(block,"data-video_title=\"","\""); if(vt.length()<1)vt=cut(block,"data-video_title='","'"); vt=txt(vt); if(vt.length()<1)vt="播放"+i; if(block.contains("data-config="))d.plays.add(new PlayItem(vt,url+"@@"+(i-1)));} if(d.plays.size()<1)d.plays.add(new PlayItem("嗅探播放",url)); return d;}
    public static String resolvePlay(String input)throws Exception{String j=input,u=""; if(j.contains("@@")){String[] sp=j.split("@@"); String html=http(sp[0]); int idx=0; try{idx=Integer.parseInt(sp[1]);}catch(Exception ignored){} String[] arr=html.split("class=\\\"dplayer\\\""); if(arr.length>idx+1){String block=arr[idx+1]; String cfg=cut(block,"data-config='","'"); if(cfg.length()<1)cfg=cut(block,"data-config=\"","\""); u=extractUrl(unescape(cfg));}} if(u.length()<1)u=extractUrl(unescape(j)); return u.length()>0?u:j;}
    static String extractUrl(String s){try{JSONObject o=new JSONObject(s); if(o.has("video")){String u=o.getJSONObject("video").optString("url",""); if(u.length()>0)return unescape(u);}}catch(Exception ignored){} Matcher m=Pattern.compile("https?://[^\\\"' ,]+?\\.(m3u8|mp4)([^\\\"' ,]*)?").matcher(s); return m.find()?unescape(m.group()):"";}
    static String abs(String u){if(u==null)u=""; if(u.startsWith("http://")||u.startsWith("https://"))return u; if(u.startsWith("//"))return "https:"+u; if(u.startsWith("/"))return currentHost+u; return currentHost+"/"+u;}
    static String txt(String s){return s==null?"":s.replaceAll("<[^>]+>"," ").replace("&nbsp;"," ").replace("&amp;","&").replace("&quot;","\"").replace("&#39;","'").replaceAll("\\s+"," ").trim();}
    static String betweenTag(String s,String a,String b){int x=s.indexOf(a); if(x<0)return""; int y=s.indexOf('>',x); if(y<0)return""; int z=s.indexOf(b,y+1); return z>y?s.substring(y+1,z):"";}
    static String cut(String s,String a,String b){int x=s.indexOf(a); if(x<0)return""; x+=a.length(); int y=s.indexOf(b,x); return y>x?s.substring(x,y):"";}
    static String meta(String h,String name){Pattern p=Pattern.compile("<meta[^>]+name=[\\\"']"+Pattern.quote(name)+"[\\\"'][^>]+content=[\\\"']([^\\\"']*)",Pattern.CASE_INSENSITIVE); Matcher m=p.matcher(h); return m.find()?m.group(1):"";}
    static String pic(String seg){int k=seg.indexOf("loadBannerDirect"); if(k<0)return""; int q1=seg.indexOf("'",k), q2=seg.indexOf("\"",k); int q=q1<0?q2:(q2<0?q1:Math.min(q1,q2)); if(q<0)return""; char c=seg.charAt(q); int e=seg.indexOf(c,q+1); return e>q?seg.substring(q+1,e):"";}
    static String unescape(String s){if(s==null)return""; return s.replace("&quot;","\"").replace("&#34;","\"").replace("&#39;","'").replace("&amp;","&").replace("\\/","/").replace("\\\\/","/");}
}
